### ISSUE TITLE
(doc) Note minimum version of Visual Studio Code for full functionality?

### ISSUE THREAD

**Issue by ferventcoder** [sohamkamani/code-eol#3]
Noticed that it was not showing EOL characters at the end of lines with text, only one empty lines. Then I upgraded Visual Studio Code and all is fine. So just wanted to give you a heads up that you might get issues on that.

**Comment by ferventcoder** [comment]
By the way, looks amazing!

**Comment by sohamkamani** [comment]
Hey thanks! I actually think this might be related to #1 . 👍

**Comment by ferventcoder** [comment]
Might be. I didn't see boxes though - just empty lines with the correct endings and nothing at the end of lines that had text
