### ISSUE TITLE
Add a setting to toggle showing eol on current line

### ISSUE THREAD

**Issue by ferventcoder** [sohamkamani/code-eol#5]
When typing, it is quite a bit jarring for the rerendering of the eol char (image?).

Can we have a setting to toggle the eol off for the current line?

**Comment by ferventcoder** [comment]
Unfortunately due to this, it made this extension unable to be used. Would you consider adding this?

**Comment by sohamkamani** [comment]
@ferventcoder  I've done one better, and fixed the jarring :)
Please update and let me know if the problem persists
